basePath: /
definitions:
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.SignInCredentials:
    properties:
      email:
        example: testUser@gmail.com
        type: string
      name:
        example: Username
        type: string
      password:
        example: userPassword
        minLength: 8
        type: string
    required:
    - email
    - name
    - password
    type: object
  models.SuccessResponse:
    properties:
      message:
        type: string
    type: object
  models.UserInfo:
    properties:
      email:
        example: testUser@gmail.com
        type: string
      id:
        type: integer
      name:
        example: TestUser
        type: string
      pancardNumber:
        example: abgjhi6789
        type: string
      password:
        example: sample11110
        minLength: 8
        type: string
      phoneNumber:
        example: "7878543610"
        type: string
    required:
    - email
    - name
    - pancardNumber
    - password
    - phoneNumber
    type: object
  models.ValidateOTPRequest:
    properties:
      email:
        type: string
      otp:
        type: string
    required:
    - email
    - otp
    type: object
  service.SignInRepository:
    type: object
host: localhost:8081
info:
  contact: {}
  description: This is a Stock Broker Application API
  title: Stock Broker Application
  version: "1.0"
paths:
  /signin:
    post:
      consumes:
      - application/json
      description: Performs validations on user sign-in credentials and verifies them.
      parameters:
      - description: User sign-in credentials
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.SignInCredentials'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully signed in
          schema:
            type: string
        "400":
          description: Failed to sign in
          schema:
            type: string
      summary: Perform sign-in validations
  /signup:
    post:
      consumes:
      - application/json
      description: Handles HTTP POST request to create new users
      parameters:
      - description: User information in JSON format
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserInfo'
      produces:
      - application/json
      responses:
        "200":
          description: User information inserted successfully
          schema:
            $ref: '#/definitions/models.SuccessResponse'
        "400":
          description: Error message
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Create a new user
  /validateOtp:
    post:
      consumes:
      - application/json
      description: Validate OTP using the provided service and repository
      parameters:
      - description: OTP validation request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.ValidateOTPRequest'
      produces:
      - application/json
      responses: {}
      summary: Validate OTP
      tags:
      - Authentication
swagger: "2.0"
